### ISSUE TITLE
Bottlepy

### ISSUE THREAD

**Issue by benboughton1** [mikeckennedy/jinja_partials#3]
Is there scope to get this working on bottlepy?
My normal stack jinja2 templating in Bottle. I'm half way through the htmx course which is pretty neat and wanted to see if I could get this to work. Cheers

**Comment by mikeckennedy** [comment]
Hi @benboughton1 I think you could definitely make this happen. You just have to slightly tweak how you initialize the jinja engine and you'd be good to go, from this [SO answer](https://stackoverflow.com/questions/28005360/bottle-py-and-jinja2-global-variable):

Two options:

```python
# At startup:
from bottle import BaseTemplate
BaseTemplate.defaults['myglobal'] = 'My global'
```

```python
# As a request wrapper:
from bottle import Jinja2Template

@hook('before_request')
def before_request():
    Jinja2Template.defaults['myglobal'] = 'My global'
```

You know Bottle better than me, would this work?

Maybe I could write a register bottle version of this:

https://github.com/mikeckennedy/jinja_partials/blob/31e813008dc60d1e8c0e7c2ad0fb6045ae54009a/jinja_partials/__init__.py#L58

What do you think?

**Comment by mikeckennedy** [comment]
Closing this since I think it's gone stale and my recommendation above could fix it. Please let me know if anyone wants me to reopen it.
