### ISSUE TITLE
Partials doesn't seem to work with flask-moment

### ISSUE THREAD

**Issue by djotaku** [mikeckennedy/jinja_partials#7]
Here's my repo: https://github.com/djotaku/taskwarrior_web

When I first load up the page, it shows the time, but if I click on any of the buttons and load in a partial page, it doesn't show anything. 

https://github.com/djotaku/taskwarrior_web/blob/cd2c95ff7f15a7a422934fa40f37f7f3332d8560/taskwarrior_web/templates/partials/task_table.html

It seems that maybe flask-moment doesn't know to be triggered again or something? I'm not 100% sure.

**Comment by mikeckennedy** [comment]
Hi Eric! I looked at the table & HTMX and it looks fine.

```python
moment(task.due).format('LLL', refresh=True)
```

That bit of code is what's not refreshing I guess? However, 100% of that code executes on the server not somehow through JS trigged by HTMX. I can't tell what's up, but I highly doubt that partials or htmx is effecting it. Maybe do a debug print on the server. 

Is the the initial statement or the ticking client-side aspect? It's possible that moment doesn't support HTMX changing the DOM (partial or not) to reattach the event.

One HTMX native fix could be to use an htmx section around that with a 1m polling refresh. But if you have 1M rows, that would be bad on the server. :)

Also see if there is some event on moment you can call to retrigger the parsing of the dom. Kind of like using jquery.click() vs. jquery.live() or whatever it was back in the day.

**Comment by djotaku** [comment]
Thanks for taking a look, Mike. Since it's not a bug with Partials, feel free to close.

**Comment by mikeckennedy** [comment]
Sure, you're welcome. I'm pretty sure it has to do with the fact that the new row/date is added after moment has a chance to parse the dom? Not 100%. Open it up again if you find it is a bug with partials.
