### ISSUE TITLE
Missing `requirements.txt` from `sdist`

### ISSUE THREAD

**Issue by jakirkham** [mikeckennedy/jinja_partials#9]
Currently `requirements.txt` is missing from the `sdist` on PyPI. As a result building from the `sdist` fails as it cannot find `requirements.txt` in `setup.py`

Would it be possible to add `requirements.txt` to `MANIFEST.in` or similar to ensure the `sdist` includes this file when created?

**Comment by jakirkham** [comment]
Here is [the CI log]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=913810&view=logs&jobId=6f142865-96c3-535c-b7ea-873d86b887bd&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823 ) with relevant traceback below:

```python
Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/conda/staged-recipes/build_artifacts/jinja_partials_1712849747428/work/setup.py", line 16, in <module>
      with open('./requirements.txt', 'r', encoding='utf-8') as fin:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
  error: subprocess-exited-with-error
```

**Comment by mikeckennedy** [comment]
Hey @jakirkham I just committed a change that I think should fix this issue. Can you double check please? The project literally have one requirement, **jinja2**, so I figure I can just put it directly into the requirements section for the setup.py.

Also: @Colelyman does the commit I just added (reference just above) fix your problem?

**Comment by mikeckennedy** [comment]
Folks, I'm also considering upgrade this to use pyproject.toml and pure wheels rather than the setup.py. Would that help or hinder your desire to add it to conda (which, thank you!)?

**Comment by Colelyman** [comment]
Thanks @mikeckennedy! I think that should fix the problem, to be completely sure a new release would need to be issued.

I can look into other conda packages that use pyproject.toml, and report back.

**Comment by mikeckennedy** [comment]
Done: https://github.com/mikeckennedy/jinja_partials/releases/tag/v0.2.1

**Comment by Colelyman** [comment]
Thanks! Any chance you would be able to push it to PyPI? The v0.2.0 release from GitHub tags worked, but it was the PyPI v0.2.0 was where the `requirements.txt` wasn't found.

**Comment by mikeckennedy** [comment]
Hi @Colelyman Yes, I just pushed it. Thanks!

**Comment by mikeckennedy** [comment]
The sdist has the fixed setup.py and I also published the wheel but it doesn't include the setup.py file. Let me know if this causes you any trouble.

**Comment by Colelyman** [comment]
Thanks @mikeckennedy, looks like it worked! (See here: https://github.com/conda-forge/staged-recipes/pull/26017)

On a different note, would you like to be added as a maintainer of the package? If so, you can comment something like "I would like to be a maintainer" in the PR and I will add you in.

**Comment by jakirkham** [comment]
Thanks Mike! 🙏

That seems like a reasonable fix

Moving to `pyproject.toml` is a good idea generally as it is more declarative. This works well on the Conda side as well

**Comment by mikeckennedy** [comment]
Great, thanks @jakirkham I already pushed the changes for the `pyproject.toml` variant. But I left the setup.py there. If you do **not** need an sdist, then I can remove the `setup.py` too.

**Comment by jakirkham** [comment]
It's still possible to build an `sdist` with `pyproject.toml`. Just need to use [`build`'s `--sdist` option]( https://build.pypa.io/en/stable/#python--m-build---sdist )

**Comment by mikeckennedy** [comment]
Sounds good. I was just trying to keep anything people may have been working with stable. I'll drop the setup.py eventually. Thanks.

**Comment by jakirkham** [comment]
Yeah for sure. Appreciate that Mike

Yeah the `sdist` is useful on the Conda packaging side as it is a source artifact with a stable checksum

The default GitHub archives are generated on demand. So their checksums can change between downloads. Using `sdist`s from PyPI avoids that issue

**Comment by mikeckennedy** [comment]
Got it. The latest version on PyPI has the fixed sdist we talked about here. Thanks!

**Comment by jakirkham** [comment]
Yep the fix works great for us. Thank you! 🙏
